---
#- name: install keys/certs
#  become: yes
#  become_user: root
#  with_items:
#    - f: '{{ etcd_pki_key_src }}'
#      d: '{{ etcd_pki_key_dest }}'
#      m: '0400'
#    - f: '{{ etcd_pki_cert_src }}'
#      d: '{{ etcd_pki_cert_dest }}'
#      m: '0600'
#    - f: '{{ etcd_pki_ca_cert_src }}'
#      d: '{{ etcd_pki_ca_cert_dest }}'
#      m: '0600'
#  copy:
#    src: '{{ item.f }}'
#    dest: '{{ item.d }}'
#    owner: '{{ etcd_user }}'
#    group: '{{ etcd_group }}'
#    mode: '{{ item.m }}'

- name: "Copy over the CA certificate"
  become: true
  copy:
    src: "./certs/{{dns_domain}}.crt"
    remote_src: False
    dest: "/var/lib/etcd/etcd-cluster-sr.pki/ca.crt"
    owner: '{{ etcd_user }}'
    group: '{{ etcd_group }}'
    mode: 0644
- name: "Copy over the `etcd` member certificate"
  become: true
  copy:
    src: ./certs/{{inventory_hostname}}.crt
    remote_src: False
    dest: /var/lib/etcd/etcd-cluster-sr.pki/server.crt
    owner: '{{ etcd_user }}'
    group: '{{ etcd_group }}'
    mode: 0644
- name: "Copy over the `etcd` member key"
  become: true
  copy:
    src: ./certs/{{inventory_hostname}}.key
    remote_src: False
    dest: /var/lib/etcd/etcd-cluster-sr.pki/server.key
    owner: '{{ etcd_user }}'
    group: '{{ etcd_group }}'
    mode: 0600
