---
- block:
    - name: Copy systemd units
      become: yes
      template:
        src: '{{item}}.j2'
        dest: '/etc/systemd/system/{{item}}'
        mode: "0644"
      with_items:
      - "etcd.service"
      - "etcd-defrag.service"
      - "etcd-defrag.timer"
      register: units

    - name: restarted services
      systemd:
        name: '{{item}}'
        state: restarted
        enabled: yes
        daemon_reload: yes
      with_items:
      - "etcd.service"
      - "etcd-defrag.timer"

  become: yes
  become_user: root